# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  home_path = ENV['HOME']
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.synced_folder "#{home_path}/.ssh", "/home/vagrant/.ssh"

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/archive.ubuntu.com/tw.archive.ubuntu.com/g' /etc/apt/sources.list
    apt-add-repository -y ppa:opencontrail/ppa
    apt-get update
    apt-get install -y iproute2 tmux netcat curl git vim python wget autoconf \
                       automake bison debhelper flex libcurl4-openssl-dev \
                       libexpat-dev libgettextpo0 libprotobuf-dev libtool libxml2-utils \
                       make protobuf-compiler python-all python-dev python-lxml \
                       python-setuptools python-sphinx ruby-ronn scons unzip vim-common \
                       libsnmp-python libipfix-dev librdkafka-dev librdkafka1 libboost-dev \
                       libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev \
                       libboost-program-options-dev libboost-python-dev libboost-regex-dev \
                       libboost-system-dev libcurl4-openssl-dev google-mock libgoogle-perftools-dev \
                       liblog4cplus-dev libtbb-dev libhttp-parser-dev libxml2-dev libicu-dev \
                       libzookeeper-mt-dev ant default-jdk javahelper libcommons-codec-java libhttpcore-java \
                       liblog4j1.2-java

    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    sudo apt-get install -y nodejs module-assistant

    mkdir /tmp/pkg
    cd /tmp/pkg
    wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver_2.2.0-1_amd64.deb
    wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver-dev_2.2.0-1_amd64.deb
    wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.7.5/libuv_1.7.5-1_amd64.deb
    dpkg -i *.deb

    curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo
    chmod a+x /usr/bin/repo
SHELL

#    config.vm.provision "shell", privileged: false, inline: <<-SHELL
#      mkdir build
#      cd build
#      repo init -u https://github.com/Juniper/contrail-vnc -b R3.2.3.x -m noauth.xml
#      repo sync
# SHELL
end
